### ISSUE TITLE
Whitespace is completely messed up

### ISSUE THREAD

**Issue by Xiretza** [Domipheus/RPU#1]
Hey! I've been following this project for quite some time, and it was a huge inspiration for building [my own RISC-V CPU](https://gitlab.com/YARM-project). However, one issue I've always had when looking at the sources here is that I just can't figure out a way to get consistent and correct indentation and alignment. There is a wild mix of spaces and tabs, but no single tab width seems to match what you must be looking at, not even in single files! If you have some special editor config for your tab stops, do tell (and maybe document it somewhere). Otherwise, I'd gladly reformat everything to be consitent, I just need to know what indentation mode you want (personally I'm a "tabs for indentation, spaces for alignment" guy, but that's a matter of taste).

**Comment by Domipheus** [comment]
Hey there, sadly there is no real point reformatting. The issue comes down to Vivado (The Xilinx tool I'm using day to day) not caring, and it's autoformatter is sadly terrible. One day I'll get around to upgrading Vivado and seeing if they fixed it, but until then, it's always going to be a massive PITA.
I'll keep this open to look at, as I do need to upgrade vivado sooner rather than later.

**Comment by Xiretza** [comment]
Oh, I see! I actually remember indentation being an issue whenever I hot-fixed something in vivado now, usually I just edited the source files directly with a proper text editor though. Here's hoping Xilinx fixes this particular long-standing major issue in their software...

**Comment by Domipheus** [comment]
I ended up running the latest source through a formatter. Let me know if it's still broken. I'll close this for now!
